name: AWS Secrets Manager for OAuth2 Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        default: 'us-west-2'
        required: false
        type: string
    outputs: 
      token_url: 
        description: 'OAuth2 token URL'
        value: ${{ jobs.get-value.outputs.token_url }}
      secret_key: 
        description: 'OAuth2 secret key'
        value: ${{ jobs.get-value.outputs.secret_key }}

jobs:
  get-value:
    name: Get OAuth2 Secret From AWS Secrets Manager and Output
    runs-on: ubuntu-20.04
    outputs:
      token_url: ${{ steps.get-value.outputs.token_url }}
      secret_key: ${{ steps.get-value.outputs.secret_key }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: false

      - name: Get and Output OAuth2 Secret Values
        id: get-value
        env:
          environment: ${{ inputs.environment }}
        run: |
          json=$(aws secretsmanager get-secret-value --secret-id /$environment/oauth2 --query SecretString --output json | jq -r .)
          echo "token_url='$(echo $json | jq -r .token_url)'" >> $GITHUB_OUTPUT
          echo "secret_key='$(echo $json | jq -r .secret_key)'" >> $GITHUB_OUTPUT
