name: Get Auth0 Client Config from AWS Secrets

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      client:
        description: 'Auth0 client secret name'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        default: 'us-west-2'
        required: false
        type: string
    outputs: 
      domain: 
        description: 'Auth0 client domain'
        value: ${{ jobs.get-value.outputs.domain }}
      audience: 
        description: 'Auth0 client audience'
        value: ${{ jobs.get-value.outputs.audience }}
      client_id:
        description: 'Auth0 client ID'
        value: ${{ jobs.get-value.outputs.client_id }}
      client_secret:
        description: 'Auth0 client secret'
        value: ${{ jobs.get-value.outputs.client_secret }}

jobs:
  get-value:
    name: Get Auth0 Client Config from AWS Secrets and Output
    runs-on: ubuntu-20.04
    outputs:
      domain: ${{ steps.get-value.outputs.domain }}
      audience: ${{ steps.get-value.outputs.audience }}
      client_id: ${{ steps.get-value.outputs.client_id }}
      client_secret: ${{ steps.get-value.outputs.client_secret }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || secrets.SIMPLE_PMP_SERVICE_USER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || secrets.SIMPLE_PMP_SERVICE_USER_KEY_SECRET }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: false

      - name: Get and Output Auth0 client secret values
        id: get-value
        env:
          environment: ${{ inputs.environment }}
          client: ${{ inputs.client }}
        run: |
          json=$(aws secretsmanager get-secret-value --secret-id $environment/auth0/$client --query SecretString --output json | jq -r .)
          echo "domain=$(echo $json | jq -r .domain)" >> $GITHUB_OUTPUT
          echo "audience=$(echo $json | jq -r .audience)" >> $GITHUB_OUTPUT
          echo "client_id=$(echo $json | jq -r .client_id)" >> $GITHUB_OUTPUT
          echo "client_secret=$(echo $json | jq -r .client_secret)" >> $GITHUB_OUTPUT
