name: AWS Secrets Manager Save Secret To File

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the secret'
        required: true
        type: string
      filename:
        description: 'Name of the file to save the secret value to'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        default: 'us-west-2'
        required: false
        type: string

jobs:
  get-value:
    name: Get Secret From AWS Secrets Manager and Save to File
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: false

      - name: Get and Output Secret Value
        id: get-value
        env:
          name: ${{ inputs.name }}
        run: |
          echo "::set-output name=value::$(aws secretsmanager get-secret-value --secret-id $name --query SecretString --output json)"

      - name: Create File with Secret Value
        env:
          value: ${{ steps.get-value.outputs.value }}
          filename: ${{ inputs.filename }}
        run: |
          (jq -r '.' <<< "${value}") > $filename
