name: AWS Secrets Manager Get Secret

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the secret'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        default: 'us-west-2'
        required: false
        type: string
      output:
        description: 'AWS CLI output type'
        default: 'text'
        required: false
        type: string
    outputs: 
      value: 
        description: 'Value of the secret'
        value: ${{ jobs.get-value.outputs.value }}

jobs:
  get-value:
    name: Get Secret From AWS Secrets Manager
    runs-on: ubuntu-20.04
    outputs:
      value: ${{ steps.get-value.outputs.value }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: false

      - name: Get and Output Secret Value
        id: get-value
        env:
          name: ${{ inputs.name }}
          output: ${{ inputs.output }}
        run: |
          echo "value=$(aws secretsmanager get-secret-value --secret-id $name --query SecretString --output $output)" >> $GITHUB_OUTPUT
