name: AWS ECS Fargate Service Restart

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment of the fargate service'
        required: true
        type: string
      owner:
        description: 'Owner of the fargate service'
        required: true
        type: string
      service:
        description: 'Name of the fargate service'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        default: 'us-west-2'
        required: false
        type: string

jobs:
  deploy:
    name: ECS Fargate Service New Deployment
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Force new Amazon ECS Service Deployment
        env:
          cluster: ${{ inputs.owner }}-${{ inputs.environment }}
          service: ${{ inputs.owner }}-${{ inputs.service }}-${{ inputs.environment }}
        run: |
          aws ecs update-service --cluster $cluster --service $service --desired-count 1 --force-new-deployment
