name: Environment Setup

on:
  workflow_call:
    inputs:
      override:
        description: 'Override environment name output'
        required: false
        type: string
    outputs: 
      name: 
        description: 'Environment'
        value: ${{ jobs.setup.outputs.name }}
      bump: 
        description: 'Which type of version bump to use'
        value: ${{ jobs.setup.outputs.bump }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-20.04
    outputs:
      name: ${{ steps.get-environment.outputs.name }}
      bump: ${{ steps.get-environment.outputs.bump }}
    steps:
      - name: Define environment and prefixes from branch name
        id: get-environment
        env:
          override: ${{ inputs.override }}
        run: |
          branch=${GITHUB_REF##*/}
          if [[ $branch == ma* ]]; then
            environment=prod
          elif [[ $branch == stag* ]]; then
            environment=stage
          elif [[ $branch == dev* ]]; then
            environment=dev
          else
            environment=dev
          fi
          echo "name=$(([[ $override != "" ]] && echo $override) || echo $environment)" >> $GITHUB_OUTPUT
          echo "bump=$(([[ $environment == "prod" ]] && echo "minor") || echo "patch")" >> $GITHUB_OUTPUT
